def _item(item_id, category, subcategory, name, price, description="", ingredients=(), pizza=False):
    return {
        "id": item_id,
        "categoria": category,
        "subcategoria": subcategory,
        "nombre": name,
        "precio": price,
        "descripcion": description,
        "ingredientes": list(ingredients),
        "es_pizza": pizza,
    }


CATEGORIES = [
    "Entradas",
    "Pizzas",
    "Salchipapas",
    "Broasters",
    "Alitas",
    "Hamburguesas",
    "Sándwiches",
    "Adicionales",
    "Jugos, batidos y café",
    "Gaseosas",
    "Cócteles",
]


MENU_ITEMS = [
    _item("pan-ajo", "Entradas", "", "Pan al Ajo (5 unid.)", 8),
    _item("pan-ajo-especial", "Entradas", "", "Pan al Ajo Especial (Queso Mozzarella, 5 unid.)", 10),
    _item("pan-yuca", "Entradas", "", "Pan de Yuca (6 unid.)", 8),
    _item("bruschettas-italianas", "Entradas", "", "Bruschettas Italianas (3 unid.)", 8),
    _item("bruschettas-mozzarella", "Entradas", "", "Bruschettas Italianas con Queso Mozzarella (3 unid.)", 10),
    _item("tequenos-mozzarella", "Entradas", "", "Tequeños Rellenos de Queso Mozzarella (10 unid.)", 12, "Con salsa de tamarindo."),
    _item("ensalada-clasica", "Entradas", "", "Ensalada Clásica", 6, "Lechuga, zanahoria y tomate."),
    _item("ensalada-especial", "Entradas", "", "Ensalada Especial", 15, "Lechuga, zanahoria, tomate, cebolla y atún."),

    _item("pizza-nutella", "Pizzas", "Italianas · 8 porciones", "Nutella", 40, pizza=True),
    _item("pizza-cuatro-estaciones", "Pizzas", "Italianas · 8 porciones", "Cuatro Estaciones", 42, ingredients=("Salsa de tomate", "Mozzarella", "Cebolla", "Alcachofas", "Champiñones", "Huevo", "Tomate", "Aceitunas", "Tocino", "Jamón", "Salami"), pizza=True),
    _item("pizza-paparella-napolitana", "Pizzas", "Italianas · 8 porciones", "Paparella Napolitana", 38, ingredients=("Salsa de tomate", "Mozzarella", "Pimiento", "Perejil", "Salchicha artesanal"), pizza=True),
    _item("pizza-vegetariana-italiana", "Pizzas", "Italianas · 8 porciones", "Vegetariana", 42, ingredients=("Salsa de tomate", "Mozzarella", "Pimiento", "Aceitunas negras y verdes", "Alcachofas", "Champiñones", "Tomate", "Albahaca"), pizza=True),
    _item("pizza-anchoas", "Pizzas", "Italianas · 8 porciones", "Anchoas", 42, ingredients=("Salsa de tomate", "Mozzarella", "Pimiento", "Tomate", "Champiñones", "Aceitunas verdes y negras", "Alcachofas", "Anchoas"), pizza=True),
    _item("pizza-cuatro-quesos-local", "Pizzas", "Italianas · 8 porciones", "Cuatro Quesos", 42, ingredients=("Salsa de tomate", "Mozzarella", "Provolone", "Dambo", "Gouda", "Parmesano", "Pimienta negra", "Perejil"), pizza=True),
    _item("pizza-espinaca-local", "Pizzas", "Italianas · 8 porciones", "Espinaca", 36, ingredients=("Salsa de tomate", "Mozzarella", "Espinaca", "Salchicha artesanal"), pizza=True),
    _item("pizza-hawaiana-personal", "Pizzas", "Personales", "Hawaiana", 20, pizza=True),
    _item("pizza-margarita-personal", "Pizzas", "Personales", "Margarita", 20, pizza=True),
    _item("pizza-jamon-personal", "Pizzas", "Personales", "Jamón", 20, pizza=True),
    _item("pizza-pepperoni-personal", "Pizzas", "Personales", "Pepperoni", 20, pizza=True),
    _item("pizza-cabanossi-personal", "Pizzas", "Personales", "Cabanossi", 20, pizza=True),
    _item("pizza-tropical-personal", "Pizzas", "Personales", "Tropical", 20, pizza=True),
    _item("pizza-salami-personal", "Pizzas", "Personales", "Salami", 20, pizza=True),

    _item("salchipapa-simple", "Salchipapas", "", "Salchipapa Simple", 8, "Papas fritas y hot dog."),
    _item("salchipapa-especial", "Salchipapas", "", "Salchipapa Especial", 10, "Papas fritas, hot dog y huevo."),
    _item("salchipapa-completa", "Salchipapas", "", "Salchipapa Completa", 14, "Papas fritas, hot dog, huevo y carne (80 g)."),

    _item("pollo-broaster", "Broasters", "", "Pollo Broaster", 15, "Papas fritas, arroz, ensalada y presa de broaster."),
    _item("pierna-bbq", "Broasters", "", "Pierna Deshuesada en Salsa BBQ", 25, "Papas fritas, ensalada y pierna de pollo."),

    _item("alitas-broaster", "Alitas", "", "Alitas Broaster", 25, "Papas fritas, salsa golf y 6 alitas."),
    _item("alitas-bbq", "Alitas", "", "Alitas BBQ", 25, "Papas fritas, salsa golf y 6 alitas."),
    _item("alitas-maracuya", "Alitas", "", "Alitas en Salsa de Maracuyá", 25, "Papas fritas, salsa golf y 6 alitas."),

    _item("pizza-burger", "Hamburguesas", "", "Pizza Burger", 22, "Lechuga, tomate, papas, queso Edam y carne (100 g)."),
    _item("hamburguesa-clasica", "Hamburguesas", "", "Hamburguesa Clásica", 5, "Lechuga, tomate, papas y carne (60 g)."),
    _item("hamburguesa-especial", "Hamburguesas", "", "Hamburguesa Especial", 10, "Lechuga, tomate, papas, huevo y carne (80 g)."),
    _item("hamburguesa-super-especial", "Hamburguesas", "", "Hamburguesa Súper Especial", 15, "Lechuga, tomate, papas, huevo, jamón, queso Edam y carne (80 g)."),
    _item("hamburguesa-hawaiana", "Hamburguesas", "", "Hamburguesa Hawaiana", 15, "Lechuga, tomate, papas, piña, queso Cheddar y carne (80 g)."),
    _item("hamburguesa-pollo", "Hamburguesas", "", "Hamburguesa de Pollo", 12, "Lechuga, tomate, papas, huevo y carne de pollo (60 g)."),
    _item("hamburguesa-choriburger", "Hamburguesas", "", "Hamburguesa Choriburger", 18, "Lechuga, tomate, papas, chorizo, queso Cheddar y carne (80 g)."),
    _item("hamburguesa-doble", "Hamburguesas", "", "Hamburguesa Doble o Nada", 18, "Lechuga, tomate, papas, huevo y doble carne (80 g)."),

    _item("sandwich-queso", "Sándwiches", "", "Sándwich de Queso", 5),
    _item("sandwich-huevo", "Sándwiches", "", "Sándwich de Huevo", 5),
    _item("sandwich-hot-dog-huevo", "Sándwiches", "", "Sándwich de Hot Dog con Huevo", 7),
    _item("sandwich-pollo", "Sándwiches", "", "Sándwich de Pollo Deshilachado", 6),
    _item("sandwich-jamon-queso", "Sándwiches", "", "Sándwich de Jamón con Queso", 6),
    _item("sandwich-huevo-tocino", "Sándwiches", "", "Sándwich de Huevo Revuelto con Tocino", 8),

    _item("adicional-carne-hamburguesa", "Adicionales", "Porciones", "Carne de hamburguesa (80 g)", 3),
    _item("adicional-hot-dog", "Adicionales", "Porciones", "Hot Dog (3 unid.)", 3),
    _item("adicional-huevo", "Adicionales", "Porciones", "Huevo Frito", 2),
    _item("adicional-cheddar", "Adicionales", "Porciones", "Queso Cheddar", 2),
    _item("adicional-presa-pollo", "Adicionales", "Porciones", "Presa de Pollo", 8),
    _item("adicional-papas", "Adicionales", "Porciones", "Papas Fritas", 6),
    _item("adicional-arroz", "Adicionales", "Porciones", "Porción de Arroz", 6),
    _item("adicional-ingrediente-pizza", "Adicionales", "Para pizzas", "Ingrediente adicional para pizza", 5, "Por cada ingrediente adicional."),
    _item("adicional-anchoas-pizza", "Adicionales", "Para pizzas", "Adicional de Anchoas para pizza", 10),
    _item("borde-queso-pizza", "Adicionales", "Para pizzas", "Borde de queso", 10, "Disponible en pizza de un solo sabor."),

    _item("jugo-papaya", "Jugos, batidos y café", "Jugos en vaso", "Jugo de Papaya", 5),
    _item("jugo-pina", "Jugos, batidos y café", "Jugos en vaso", "Jugo de Piña", 5),
    _item("jugo-fresa", "Jugos, batidos y café", "Jugos en vaso", "Jugo de Fresa", 8),
    _item("jugo-mango", "Jugos, batidos y café", "Jugos en vaso", "Jugo de Mango", 10),
    _item("jugo-lucuma", "Jugos, batidos y café", "Jugos en vaso", "Jugo de Lúcuma", 10),
    _item("jugo-maracumango", "Jugos, batidos y café", "Jugos en vaso", "Jugo de Maracumango", 10),
    _item("jugo-combinado", "Jugos, batidos y café", "Jugos en vaso", "Jugo Combinado", 10, "Papaya, piña, manzana y plátano."),
    _item("litro-pina", "Jugos, batidos y café", "Jugos en jarra · 1 litro", "Litro de Piña", 15),
    _item("litro-limonada", "Jugos, batidos y café", "Jugos en jarra · 1 litro", "Litro de Limonada", 15),
    _item("litro-limonada-menta", "Jugos, batidos y café", "Jugos en jarra · 1 litro", "Litro de Limonada con Menta", 17),
    _item("litro-maracuya", "Jugos, batidos y café", "Jugos en jarra · 1 litro", "Litro de Maracuyá", 18),
    _item("litro-maracumango", "Jugos, batidos y café", "Jugos en jarra · 1 litro", "Litro de Maracumango", 20),
    _item("batido-papaya", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Papaya", 10),
    _item("batido-fresa", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Fresa", 10),
    _item("batido-platano", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Plátano", 10),
    _item("batido-mango", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Mango", 12),
    _item("batido-durazno", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Durazno", 14),
    _item("batido-arandano", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Arándano", 15),
    _item("batido-maracumango", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Maracumango", 15),
    _item("batido-lucuma", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Lúcuma", 15),
    _item("batido-fresa-mango", "Jugos, batidos y café", "Batidos con leche · vaso", "Batido de Fresa con Mango", 15),
    _item("adicional-fruta-batido", "Jugos, batidos y café", "Adicionales", "Fruto adicional para batido", 5, "Adicional de cualquier fruto."),
    _item("cafe-instantaneo", "Jugos, batidos y café", "Café e infusiones", "Café Instantáneo", 3),
    _item("cafe-maquina", "Jugos, batidos y café", "Café e infusiones", "Café de Máquina", 6),
    _item("cafe-leche", "Jugos, batidos y café", "Café e infusiones", "Café con Leche", 10, "Precio según menú del local."),
    _item("cafe-expresso", "Jugos, batidos y café", "Café e infusiones", "Café Exprés", 6),
    _item("cafe-cappuccino", "Jugos, batidos y café", "Café e infusiones", "Café Cappuccino", 10),
    _item("chocolate-puro", "Jugos, batidos y café", "Café e infusiones", "Chocolate Puro", 5),
    _item("chocolate-leche", "Jugos, batidos y café", "Café e infusiones", "Chocolate con Leche", 10),
    _item("taza-leche", "Jugos, batidos y café", "Café e infusiones", "Taza de Leche", 6),
    _item("infusion-anis", "Jugos, batidos y café", "Infusiones", "Infusión de Anís", 3),
    _item("infusion-manzanilla", "Jugos, batidos y café", "Infusiones", "Infusión de Manzanilla", 3),
    _item("infusion-hierba-luisa", "Jugos, batidos y café", "Infusiones", "Infusión de Hierba Luisa", 3),
    _item("infusion-te-puro", "Jugos, batidos y café", "Infusiones", "Té Puro", 3),
    _item("infusion-te-canela-clavo", "Jugos, batidos y café", "Infusiones", "Té con Canela y Clavo", 3),

    _item("coca-cola-300ml", "Gaseosas", "300 ml", "Coca Cola", 3),
    _item("inca-kola-300ml", "Gaseosas", "300 ml", "Inca Kola", 3),
    _item("fanta-300ml", "Gaseosas", "300 ml", "Fanta", 3),
    _item("sprite-300ml", "Gaseosas", "300 ml", "Sprite", 3),
    _item("coca-cola-medio-litro", "Gaseosas", "Medio litro", "Coca Cola", 4),
    _item("inca-kola-medio-litro", "Gaseosas", "Medio litro", "Inca Kola", 4),
    _item("fanta-medio-litro", "Gaseosas", "Medio litro", "Fanta", 4),
    _item("inca-kola-gordita", "Gaseosas", "625 ml", "Inca Kola Gordita", 6),
    _item("coca-cola-litro", "Gaseosas", "1 litro", "Coca Cola", 7),
    _item("inca-kola-litro", "Gaseosas", "1 litro", "Inca Kola", 7),
    _item("fanta-litro", "Gaseosas", "1 litro", "Fanta", 7),
    _item("coca-cola-litro-y-medio", "Gaseosas", "1.5 litros", "Coca Cola", 10),
    _item("inca-kola-litro-y-medio", "Gaseosas", "1.5 litros", "Inca Kola", 10),
    _item("agua-natural", "Gaseosas", "750 ml", "Agua Natural San Luis", 2.5),
    _item("agua-gas", "Gaseosas", "625 ml", "Agua con Gas San Luis", 2.5),

    _item("coctel-pisco-sour", "Cócteles", "", "Pisco Sour Clásico", 18),
    _item("coctel-pisco-sour-arandanos", "Cócteles", "", "Pisco Sour de Arándanos", 22),
    _item("coctel-pisco-sour-maracuya", "Cócteles", "", "Pisco Sour de Maracuyá", 22),
    _item("coctel-chilcano", "Cócteles", "", "Chilcano Clásico", 15),
    _item("coctel-chilcano-maracuya", "Cócteles", "", "Chilcano de Maracuyá", 18),
    _item("coctel-cuba-libre", "Cócteles", "", "Cuba Libre", 13),
    _item("coctel-mojito", "Cócteles", "", "Mojito", 15),
    _item("coctel-caipiroska", "Cócteles", "", "Caipiroska", 16),
    _item("coctel-daiquiri", "Cócteles", "", "Daiquiri Clásico", 15),
    _item("coctel-daiquiri-fresa", "Cócteles", "", "Daiquiri de Fresa", 17),
    _item("coctel-margarita", "Cócteles", "", "Margarita", 18),
    _item("coctel-pina-colada", "Cócteles", "", "Piña Colada", 20),
    _item("coctel-algarrobina", "Cócteles", "", "Algarrobina", 18),
    _item("coctel-desestresante", "Cócteles", "", "Desestresante", 20),
]


CATEGORY_ORDER = {category: index for index, category in enumerate(CATEGORIES)}

OBSOLETE_MENU_ITEM_IDS = {
    "infusiones",
    "gaseosa-300ml",
    "gaseosa-medio-litro",
    "gaseosa-litro",
    "gaseosa-litro-y-medio",
}